version: "3"

services:
  backend:
    environment:
      - BACKEND_MODE=${BACKEND_MODE:-production}
      - BACKEND_PORT=${BACKEND_PORT:-5000}
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        - BACKEND_MODE=${BACKEND_MODE}
        - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: unless-stopped
    container_name: redrawer_backend

  frontend:
    depends_on:
      - backend
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-7000}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:5000}
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - BACKEND_URL=${BACKEND_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: unless-stopped
    container_name: redrawer_frontend
