version: "3"

services:
  backend:
    build: backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    container_name: redrawer_backend

  frontend:
    depends_on:
      - backend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=${BACKEND_URL}
    ports:
      - "7000:7000"
    restart: unless-stopped
    container_name: redrawer_frontend
